pipelines:
  - name: Run_Description_Feature
    steps: 
      - name: Set_Run_Description
        type: Bash
        execution:
          onStart:
            - update_run_description 'build started'
      - name: Update_Run_Description
        type: Bash
        configuration:
          inputSteps:
            - name: Set_Run_Description
        execution:
          onExecute:
            - echo 'Build is in progress'
            - update_run_description 'build in progress'
            - sleep 15s
          onComplete:
            - echo 'Updating run description'
            - update_run_description 'Build is completed'
