template: true
valuesFilePath: ./values.yml

resources:
  - name: broadcom_task_gitrepo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitIntegration }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: https

pipelines:
  - name: broadcom_task_test
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          RESOLVE_REPO: npm-virtual
    steps:
      - name: test_task
        type: Bash
        configuration:
          inputResources:
            - name: broadcom_task_gitrepo
          integrations:
            - name: {{ .Values.artIntegration }}
        execution:
          onExecute:
            - pushd $res_broadcom_task_gitrepo_resourcePath
            # Configure JFrog CLI
            - jfrog npmc --repo-resolve $RESOLVE_REPO
            # Install npm dependencies
            - jfrog npm install
            # Build task runnable script bundled with dependencies
            - npm run dist
            - popd

            # Run task
            - task: $res_broadcom_task_gitrepo_resourcePath
              id: broadcom_test
              input:
                name: "developer"

            # Check task output
            - echo "task output is $OUT_broadcom_test_greeting"
            # Check exported environment variable
            - echo "path to greeting file is $GREETING_FILE"
            # Check task generated file
            - cat ./greeting.txt
          onComplete:
            - echo "Step done!"

{{ if .Values.windowsNodePool }}
  - name: broadcom_task_win_test
    configuration:
      jfrogCliVersion: 2
      nodePool: {{ .Values.windowsNodePool }}
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-w19node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          RESOLVE_REPO: npm-virtual
    steps:
      - name: win_test_task
        type: PowerShell
        configuration:
          inputResources:
            - name: broadcom_task_gitrepo
          integrations:
            - name: {{ .Values.artIntegration }}
        execution:
          onExecute:
            - pushd $res_broadcom_task_gitrepo_resourcePath
            # Configure JFrog CLI
            - jfrog npmc --repo-resolve $RESOLVE_REPO
            # Install npm dependencies
            - jfrog npm install
            # Build task runnable script bundled with dependencies
            - npm run dist
            - popd

            # Run task
            - task: $res_broadcom_task_gitrepo_resourcePath
              id: broadcom_test
              input:
                name: "developer"

            # Check task output
            - echo "task output is ${OUT_broadcom_test_greeting}"
            # Check exported environment variable
            - echo "path to greeting file is ${GREETING_FILE}"
            # Check task generated file
            - Get-Content ./greeting.txt
          onComplete:
            - echo "Step done!"
{{ end }}